# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

schedules:
- cron: "30 13 * * Mon,Tue,Wed,Thu,Fri"
  displayName: "Daily 13:30 UTC build (9:30 EST)"
  branches:
    include:
    - master
  always: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'Install'

- script: npm run build
  displayName: 'Build'

- script: node lib/emailer.js
  displayName: 'Find stale PRs and email results'
  env:
    username: $(USERNAME)
    password: $(PASSWORD)
    recipient: $(TO_EMAIL)
    azp_token: $(AZP_TOKEN)
  condition: eq(variables['Build.Reason'], 'Schedule')

- script: npm run start
  displayName: 'Find stale PRs'
  env:
    azp_token: $(AZP_TOKEN)
  condition: ne(variables['Build.Reason'], 'Schedule')
